trigger:
  - main

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: ranbirlab/testapp
      ref: main
      endpoint: 'github.com_negiranbir109'

jobs:
  - template: azure-pipelines/templates/build.yml@templates
    parameters:
      agent_pool_name: 'ubuntu-latest'
      publish_artifact_contents: |
                                .terraform.lock.hcl
                                *.tf
                                environments/**
