trigger:
- main

pr: none

resources:
  repositories:
    - repository: templates
      type: github
      name: KPMG-UK/ewt-engineering-azure-infrastructure-template
      ref: 'fix/self-hosted-pool'
      endpoint: 'Migrate Squad Sandbox'

jobs:
- template: .azure-pipelines/templates/build.yml@templates
  parameters:
    agent_pool_name: 'tax-stg-prd'
    publish_artifact_contents: |
                              .terraform.lock.hcl
                              *.tf
                              modules/**
                              environments/**