trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      name: ranbirlab/testapp
      ref: main
      endpoint: 'github.com_negiranbir109'

stages:
  - template: .azure-pipelines/templates/multi-stage-deployment.yml@templates
    parameters:
      agent_pool_name: 'ubuntu-latest'
      deployment_environment: 'TaxStaging'
      azure_resource_manager_connection: '<new_azure_resource_manager_connection>'
      project_id: '<new_project_id>'
      artifact_published_pipeline_id: '<new_artifact_published_pipeline_id>'
      publish_artifact_name: '<new_publish_artifact_name>'
      tf_az_backend_resource_group_name: 'TF-Backend-RG'
      tf_az_backend_storage_account_name: 'tfdemobackend
      tf_az_backend_container_name: 'tax-tfstate'
      tf_az_backend_state_file_name: 'state.tfstate'
      tf_variables: |
                  -var-file="./environments/staging-tfvars.cfg"
