trigger: none

resources:
  repositories:
    - repository: templates
      type: github
      name: KPMG-UK/ewt-engineering-azure-infrastructure-template
      ref: 'fix/self-hosted-pool'
      endpoint: 'Migrate Squad Sandbox'

stages:
- template: .azure-pipelines/templates/multi-stage-deployment.yml@templates
  parameters:
    agent_pool_name: 'tax-stg-prd'
    deployment_environment: 'TaxStaging'
    azure_resource_manager_connection: 'uk-ewt-tax-pipeline'
    project_id: 'c87302c7-ffbd-4d51-8e80-5b57ffa46d40'
    artifact_published_pipeline_id: '112'
    publish_artifact_name: 'drop'
    tf_az_backend_resource_group_name: 'uk-uks-tax-stg-rg-mvp-tfstate'
    tf_az_backend_storage_account_name: 'ukazrsttaxstgmvptf1010'
    tf_az_backend_container_name: 'terraform-state'
    tf_az_backend_state_file_name: 'state.tfstate'
    tf_variables: |
                -var-file="./environments/staging-tfvars.cfg"